version: 2

project_name: supervisord

env:
  - GO111MODULE=on

before:
  hooks:
    - go generate ./...
    - go mod download

builds:

  - id: dynamic
    binary: supervisord
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
    flags:
      - -tags=release
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"

archives:

  - id: archive_multi
    ids: [dynamic]
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    wrap_in_directory: true
    files:
      - none*

release:
  github:
    owner: jbox-web
    name: supervisord
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
